<?php

namespace Database\Seeders;

use App\Models\BonusCard;
use Illuminate\Database\Seeder;

class BonusCardSeeder extends Seeder
{
    public function run(): void
    {
        $cards = [
            // ── Stamina (Self) ─────────────────────────────────
            [
                'name'            => 'Séance de récupération',
                'description'     => 'Restaure 20 points de stamina à tous les joueurs de l\'effectif.',
                'tier'            => 'bronze',
                'target'          => 'self',
                'execution_phase' => 'immediate',
                'effect_type'     => 'stamina_boost',
                'effect_value'    => ['amount' => 20],
                'cost'            => 200,
                'base_weight'     => 150,
                'icon'            => '💊',
            ],
            [
                'name'            => 'Stage intensif',
                'description'     => 'Restaure 30 points de stamina à tous les joueurs de l\'effectif.',
                'tier'            => 'silver',
                'target'          => 'self',
                'execution_phase' => 'immediate',
                'effect_type'     => 'stamina_boost',
                'effect_value'    => ['amount' => 30],
                'cost'            => 400,
                'base_weight'     => 100,
                'icon'            => '🏃',
            ],
            [
                'name'            => 'Préparation olympique',
                'description'     => 'Restaure 40 points de stamina à tous les joueurs de l\'effectif.',
                'tier'            => 'gold',
                'target'          => 'self',
                'execution_phase' => 'immediate',
                'effect_type'     => 'stamina_boost',
                'effect_value'    => ['amount' => 40],
                'cost'            => 700,
                'base_weight'     => 50,
                'icon'            => '🏅',
            ],

            // ── Blessure (Player) ──────────────────────────────
            [
                'name'            => 'Kiné express',
                'description'     => 'Réduit de 2 semaines la durée d\'indisponibilité d\'un joueur blessé.',
                'tier'            => 'bronze',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'injury_reduce',
                'effect_value'    => ['weeks' => 2],
                'cost'            => 250,
                'base_weight'     => 120,
                'icon'            => '🩹',
            ],
            [
                'name'            => 'Chirurgie accélérée',
                'description'     => 'Réduit de 4 semaines la durée d\'indisponibilité d\'un joueur blessé.',
                'tier'            => 'silver',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'injury_reduce',
                'effect_value'    => ['weeks' => 4],
                'cost'            => 500,
                'base_weight'     => 80,
                'icon'            => '🏥',
            ],
            [
                'name'            => 'Miracle médical',
                'description'     => 'Guérit immédiatement un joueur blessé, quelle que soit la durée restante.',
                'tier'            => 'gold',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'injury_cure',
                'effect_value'    => ['weeks' => 999],
                'cost'            => 800,
                'base_weight'     => 30,
                'icon'            => '✨',
            ],

            // ── Finance — Pub (pari : gain aléatoire ±) ─────────
            [
                'name'            => 'Affiche locale',
                'description'     => 'Campagne d\'affichage au résultat incertain : rapporte entre -100 € et +400 € au budget.',
                'tier'            => 'bronze',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_gamble',
                'effect_value'    => ['min' => -100, 'max' => 400],
                'cost'            => 150,
                'base_weight'     => 80,
                'icon'            => '📣',
            ],
            [
                'name'            => 'Spot TV',
                'description'     => 'Spot télévisé au résultat incertain : rapporte entre -300 € et +900 € au budget.',
                'tier'            => 'silver',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_gamble',
                'effect_value'    => ['min' => -300, 'max' => 900],
                'cost'            => 300,
                'base_weight'     => 60,
                'icon'            => '📺',
            ],
            [
                'name'            => 'Campagne nationale',
                'description'     => 'Grande campagne nationale au résultat incertain : rapporte entre -500 € et +2200 € au budget. Coup de pouce pour les équipes en difficulté.',
                'tier'            => 'gold',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_gamble',
                'effect_value'    => ['min' => -500, 'max' => 2200],
                'cost'            => 600,
                'base_weight'     => 30,
                'icon'            => '🎰',
            ],

            // ── Finance — Sponsor (défi : récompense si objectif atteint au prochain match) ──
            [
                'name'            => 'Prime de victoire',
                'description'     => 'Le sponsor verse +600 € si tu gagnes ton prochain match. Sinon, la mise est perdue.',
                'tier'            => 'bronze',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_challenge',
                'effect_value'    => ['challenge' => 'win', 'reward' => 600],
                'cost'            => 200,
                'base_weight'     => 70,
                'icon'            => '🥅',
            ],
            [
                'name'            => 'Prime offensive',
                'description'     => 'Le sponsor verse +1200 € si ton équipe marque au moins 3 buts au prochain match. Sinon, la mise est perdue.',
                'tier'            => 'silver',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_challenge',
                'effect_value'    => ['challenge' => 'score_3', 'reward' => 1200],
                'cost'            => 300,
                'base_weight'     => 60,
                'icon'            => '⚽',
            ],
            [
                'name'            => 'Prime défensive',
                'description'     => 'Le sponsor verse +1200 € si ton équipe n\'encaisse aucun but au prochain match. Sinon, la mise est perdue.',
                'tier'            => 'silver',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_challenge',
                'effect_value'    => ['challenge' => 'clean_sheet', 'reward' => 1200],
                'cost'            => 300,
                'base_weight'     => 60,
                'icon'            => '🛡️',
            ],
            [
                'name'            => 'Prime du spectacle',
                'description'     => 'Le sponsor verse +1400 € si tu gagnes ton prochain match avec au moins 2 buts d\'écart. Sinon, la mise est perdue.',
                'tier'            => 'silver',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_challenge',
                'effect_value'    => ['challenge' => 'win_by_2', 'reward' => 1400],
                'cost'            => 350,
                'base_weight'     => 50,
                'icon'            => '🎇',
            ],
            [
                'name'            => 'Méga-contrat',
                'description'     => 'Le sponsor verse +2500 € si tu gagnes ton prochain match en marquant au moins 3 buts. Sinon, la mise est perdue.',
                'tier'            => 'gold',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_challenge',
                'effect_value'    => ['challenge' => 'win_score_3', 'reward' => 2500],
                'cost'            => 600,
                'base_weight'     => 25,
                'icon'            => '🏆',
            ],

            // ── Boost match (Match / pre_match) ────────────────
            [
                'name'            => 'Motivation pré-match',
                'description'     => '+5 en attaque pour tous les joueurs lors du prochain match.',
                'tier'            => 'bronze',
                'target'          => 'match',
                'execution_phase' => 'pre_match',
                'effect_type'     => 'stat_boost',
                'effect_value'    => ['stat' => 'attack', 'amount' => 5],
                'cost'            => 200,
                'base_weight'     => 120,
                'icon'            => '📣',
            ],
            [
                'name'            => 'Discours du coach',
                'description'     => '+10 en attaque pour tous les joueurs lors du prochain match.',
                'tier'            => 'silver',
                'target'          => 'match',
                'execution_phase' => 'pre_match',
                'effect_type'     => 'stat_boost',
                'effect_value'    => ['stat' => 'attack', 'amount' => 10],
                'cost'            => 400,
                'base_weight'     => 80,
                'icon'            => '🎤',
            ],
            [
                'name'            => 'Mental d\'acier',
                'description'     => '+15 en attaque et +20 stamina pour tous les joueurs lors du prochain match.',
                'tier'            => 'gold',
                'target'          => 'match',
                'execution_phase' => 'pre_match',
                'effect_type'     => 'stat_boost_and_stamina',
                'effect_value'    => ['stat' => 'attack', 'amount' => 15, 'stamina_bonus' => 20],
                'cost'            => 700,
                'base_weight'     => 30,
                'icon'            => '🔥',
            ],

            // ── Moral (Player) ─────────────────────────────────
            [
                'name'            => 'Mot d\'encouragement',
                'description'     => 'Redonne 10 points de moral à un joueur.',
                'tier'            => 'bronze',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'morale_boost',
                'effect_value'    => ['amount' => 10],
                'cost'            => 200,
                'base_weight'     => 120,
                'icon'            => '💬',
            ],
            [
                'name'            => 'Entretien individuel',
                'description'     => 'Redonne 20 points de moral à un joueur.',
                'tier'            => 'silver',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'morale_boost',
                'effect_value'    => ['amount' => 20],
                'cost'            => 400,
                'base_weight'     => 80,
                'icon'            => '🗣️',
            ],
            [
                'name'            => 'Soutien psychologique',
                'description'     => 'Redonne 35 points de moral à un joueur.',
                'tier'            => 'gold',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'morale_boost',
                'effect_value'    => ['amount' => 35],
                'cost'            => 700,
                'base_weight'     => 30,
                'icon'            => '🧠',
            ],

            // ── Relation coach (Player) ────────────────────────
            [
                'name'            => 'Geste de confiance',
                'description'     => 'Améliore de 10 points la relation d\'un joueur avec le coach.',
                'tier'            => 'bronze',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'coach_affinity_boost',
                'effect_value'    => ['amount' => 10],
                'cost'            => 200,
                'base_weight'     => 120,
                'icon'            => '🤝',
            ],
            [
                'name'            => 'Vote de confiance',
                'description'     => 'Améliore de 20 points la relation d\'un joueur avec le coach.',
                'tier'            => 'silver',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'coach_affinity_boost',
                'effect_value'    => ['amount' => 20],
                'cost'            => 400,
                'base_weight'     => 80,
                'icon'            => '💛',
            ],
            [
                'name'            => 'Lien indéfectible',
                'description'     => 'Améliore de 35 points la relation d\'un joueur avec le coach.',
                'tier'            => 'gold',
                'target'          => 'player',
                'execution_phase' => 'immediate',
                'effect_type'     => 'coach_affinity_boost',
                'effect_value'    => ['amount' => 35],
                'cost'            => 700,
                'base_weight'     => 30,
                'icon'            => '🫂',
            ],

            // ══════════════════════════════════════════════════
            //   CARTES MALUS — ciblent l'adversaire du prochain match
            // ══════════════════════════════════════════════════

            // ── Fatigue (−stamina aux titulaires adverses) ─────
            [
                'name'            => 'Nuit agitée',
                'description'     => 'Retire 15 points de stamina aux titulaires de votre adversaire avant son prochain match.',
                'kind'            => 'malus',
                'tier'            => 'bronze',
                'target'          => 'opponent',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_stamina_drain',
                'effect_value'    => ['amount' => 15],
                'cost'            => 250,
                'base_weight'     => 90,
                'icon'            => '😴',
            ],
            [
                'name'            => 'Sabotage du sommeil',
                'description'     => 'Retire 25 points de stamina aux titulaires de votre adversaire avant son prochain match.',
                'kind'            => 'malus',
                'tier'            => 'silver',
                'target'          => 'opponent',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_stamina_drain',
                'effect_value'    => ['amount' => 25],
                'cost'            => 450,
                'base_weight'     => 70,
                'icon'            => '🥱',
            ],
            [
                'name'            => 'Épuisement programmé',
                'description'     => 'Retire 35 points de stamina aux titulaires de votre adversaire avant son prochain match.',
                'kind'            => 'malus',
                'tier'            => 'gold',
                'target'          => 'opponent',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_stamina_drain',
                'effect_value'    => ['amount' => 35],
                'cost'            => 750,
                'base_weight'     => 35,
                'icon'            => '🪫',
            ],

            // ── Titulaire consigné (interdit de titularisation) ─
            [
                'name'            => 'Convocation surprise',
                'description'     => 'Un titulaire au hasard de votre adversaire ne pourra pas débuter son prochain match.',
                'kind'            => 'malus',
                'tier'            => 'silver',
                'target'          => 'opponent',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_bench_starter',
                'effect_value'    => ['count' => 1, 'pick' => 'random'],
                'cost'            => 550,
                'base_weight'     => 60,
                'icon'            => '🚫',
            ],
            [
                'name'            => 'Scandale médiatique',
                'description'     => 'Un cadre de votre adversaire (son meilleur titulaire de champ) ne pourra pas débuter son prochain match.',
                'kind'            => 'malus',
                'tier'            => 'gold',
                'target'          => 'opponent',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_bench_starter',
                'effect_value'    => ['count' => 1, 'pick' => 'key'],
                'cost'            => 900,
                'base_weight'     => 30,
                'icon'            => '📰',
            ],

            // ── Malus à cible choisie (équipe au choix / leader) ───
            [
                'name'            => 'Coup monté',
                'description'     => 'Choisissez une équipe : un de ses titulaires au hasard ne pourra pas débuter son prochain match.',
                'kind'            => 'malus',
                'tier'            => 'silver',
                'target'          => 'team',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_bench_starter',
                'effect_value'    => ['count' => 1, 'pick' => 'random', 'target_mode' => 'select'],
                'cost'            => 650,
                'base_weight'     => 50,
                'icon'            => '🎯',
            ],
            [
                'name'            => 'Sabotage ciblé',
                'description'     => 'Choisissez une équipe : retire 25 points de stamina à ses titulaires avant son prochain match.',
                'kind'            => 'malus',
                'tier'            => 'silver',
                'target'          => 'team',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_stamina_drain',
                'effect_value'    => ['amount' => 25, 'target_mode' => 'select'],
                'cost'            => 550,
                'base_weight'     => 50,
                'icon'            => '😈',
            ],
            [
                'name'            => 'Abattre le favori',
                'description'     => 'Cible automatiquement le 1er du classement : son meilleur titulaire de champ ne pourra pas débuter son prochain match.',
                'kind'            => 'malus',
                'tier'            => 'gold',
                'target'          => 'team',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_bench_starter',
                'effect_value'    => ['count' => 1, 'pick' => 'key', 'target_mode' => 'leader'],
                'cost'            => 700,
                'base_weight'     => 35,
                'icon'            => '👑',
            ],

            // ══════════════════════════════════════════════════
            //   CARTES BONUS — profondeur (cohésion, économie, défense)
            // ══════════════════════════════════════════════════
            [
                'name'            => 'Cellule de crise',
                'description'     => 'Pose un bouclier : le prochain malus infligé à votre équipe sera automatiquement annulé.',
                'kind'            => 'bonus',
                'tier'            => 'silver',
                'target'          => 'self',
                'execution_phase' => 'immediate',
                'effect_type'     => 'malus_shield',
                'effect_value'    => [],
                'cost'            => 400,
                'base_weight'     => 70,
                'icon'            => '🛡️',
            ],
            [
                'name'            => 'Esprit d\'équipe',
                'description'     => 'Séminaire de cohésion : +15 de moral à tous les joueurs de l\'effectif.',
                'kind'            => 'bonus',
                'tier'            => 'silver',
                'target'          => 'self',
                'execution_phase' => 'immediate',
                'effect_type'     => 'team_morale_boost',
                'effect_value'    => ['amount' => 15],
                'cost'            => 450,
                'base_weight'     => 70,
                'icon'            => '💛',
            ],
            [
                'name'            => 'Vente de maillots',
                'description'     => 'Revenu indexé sur votre dernier match : 200 € + 150 €/but marqué + 500 € si victoire.',
                'kind'            => 'bonus',
                'tier'            => 'silver',
                'target'          => 'finance',
                'execution_phase' => 'immediate',
                'effect_type'     => 'revenue_performance',
                'effect_value'    => ['base' => 200, 'per_goal' => 150, 'win_bonus' => 500],
                'cost'            => 300,
                'base_weight'     => 60,
                'icon'            => '👕',
            ],

            // ══════════════════════════════════════════════════
            //   CARTES MALUS — moral / relation / économie (cible variable)
            // ══════════════════════════════════════════════════
            [
                'name'            => 'Guerre psychologique',
                'description'     => 'Sape le moral de l\'adversaire de votre prochain match : −15 de moral à tout son effectif.',
                'kind'            => 'malus',
                'tier'            => 'silver',
                'target'          => 'opponent',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_morale_drain',
                'effect_value'    => ['amount' => 15],
                'cost'            => 450,
                'base_weight'     => 55,
                'icon'            => '😤',
            ],
            [
                'name'            => 'Tapage médiatique',
                'description'     => 'Choisissez une équipe : −30 de relation entre son cadre (meilleur joueur de champ) et son coach.',
                'kind'            => 'malus',
                'tier'            => 'silver',
                'target'          => 'team',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_affinity_drain',
                'effect_value'    => ['amount' => 30, 'target_mode' => 'select'],
                'cost'            => 500,
                'base_weight'     => 50,
                'icon'            => '🗞️',
            ],
            [
                'name'            => 'Contrôle fiscal',
                'description'     => 'Cible automatiquement le 1er du classement : −600 € sur son budget.',
                'kind'            => 'malus',
                'tier'            => 'gold',
                'target'          => 'team',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_budget_drain',
                'effect_value'    => ['amount' => 600, 'target_mode' => 'leader'],
                'cost'            => 550,
                'base_weight'     => 35,
                'icon'            => '💸',
            ],

            // ── Malus "ce match" : debuff de stats sur la cible ─
            [
                'name'            => 'Pelouse sabotée',
                'description'     => 'Terrain gras : −12 de vitesse à toute l\'équipe de votre prochain adversaire, pour ce match.',
                'kind'            => 'malus',
                'tier'            => 'silver',
                'target'          => 'opponent',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_team_stat_debuff',
                'effect_value'    => ['stat' => 'speed', 'amount' => 12],
                'cost'            => 500,
                'base_weight'     => 50,
                'icon'            => '🌧️',
            ],
            [
                'name'            => 'Marquage à la culotte',
                'description'     => 'Choisissez une équipe : son cadre (meilleur joueur de champ) joue son prochain match avec −15 en attaque et −15 au tir.',
                'kind'            => 'malus',
                'tier'            => 'silver',
                'target'          => 'team',
                'execution_phase' => 'immediate',
                'effect_type'     => 'opponent_key_stat_debuff',
                'effect_value'    => ['stats' => ['attack' => 15, 'shot' => 15], 'target_mode' => 'select'],
                'cost'            => 550,
                'base_weight'     => 45,
                'icon'            => '🥅',
            ],

            // ── Boosts d'équipe "ce match" (hook pre_match) ─────
            [
                'name'            => 'Bloc défensif',
                'description'     => '+10 en défense pour tous les joueurs lors du prochain match.',
                'kind'            => 'bonus',
                'tier'            => 'silver',
                'target'          => 'match',
                'execution_phase' => 'pre_match',
                'effect_type'     => 'stat_boost',
                'effect_value'    => ['stat' => 'defense', 'amount' => 10],
                'cost'            => 400,
                'base_weight'     => 70,
                'icon'            => '🧱',
            ],
            [
                'name'            => 'Pressing intense',
                'description'     => '+8 en vitesse pour tous les joueurs lors du prochain match.',
                'kind'            => 'bonus',
                'tier'            => 'silver',
                'target'          => 'match',
                'execution_phase' => 'pre_match',
                'effect_type'     => 'stat_boost',
                'effect_value'    => ['stat' => 'speed', 'amount' => 8],
                'cost'            => 380,
                'base_weight'     => 65,
                'icon'            => '⚡',
            ],
        ];

        // Anciennes cartes finance "argent gratuit" remplacées par les paris/défis.
        // Le FK game_bonus_cards.bonus_card_id est en cascadeOnDelete : supprimer
        // ces cartes retire aussi les exemplaires déjà achetés dans les parties.
        BonusCard::whereIn('name', ['Bonus sponsors', 'Contrat TV', 'Méga-sponsor'])->delete();

        foreach ($cards as $card) {
            BonusCard::updateOrCreate(['name' => $card['name']], $card);
        }
    }
}
